image: gitlab.capsrv.xyz:5000/android-ci:latest

stages:
- test
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

gradlew_test:
  stage: test
  tags:
    - testing-apk
  script:
  - ./gradlew test
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}_${CI_JOB_NAME}_${CI_JOB_ID}"
    when: always
    paths:
      - app/build/reports/
    expire_in: 1 day
    
android_build:
  stage: build
  tags:
    - testing-apk
  script:
    - ./gradlew clean assembleDebug
    - cp app/build/outputs/apk/debug/*.apk /opt/build/
  artifacts:
    name: "build_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}_${CI_JOB_NAME}_${CI_JOB_ID}"
    when: always
    paths:
      - app/build/outputs/apk/
    expire_in: 1 day