image: gitlab.capsrv.xyz:5000/android-ci:latest

stages:
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  stage: build
  tags:
    - docker-dev
  script:
  - ./gradlew check