image: gradle:alpine


stages:
  - version
  - test



unitTests:
  stage: test
  script:
    - ./gradle test
  tags:
    - docker-dev

Test:
  stage: version
  script:
    - ./gradle --version
  tags:
    - docker-dev