image: gradle:alpine

stages:
  - version
  - test



unitTests:
  stage: test
  script:
    - gradlew test
  tags:
    - docker-dev

Test:
  stage: version
  script:
    - gradlew --version
  tags:
    - docker-dev